import Head from "next/head";
import Layout from "../components/Layout";
import Hero from "../components/Hero";
import css from "../styles/Home.module.css";
import Services from "../components/Services";
import { client } from "../lib/client";
import Burger from "../components/Burger";
import Drink from "../components/Drink";
import Menu from "../components/Menu";
import Pasta from "../components/Pasta";
import Salad from "../components/Salad";
import pizza from "../sanity/schemas/pizza";

export default function Home({ pizzas, burgers, pastas, salads, drinks }) {
  return (
    <Layout>
      <div className={css.container}>
        <Head>
          <title>ĐỒ ĂN NHANH</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png" />
        </Head>
        {/*body */}
        <main>
          <Hero />
          <Services />
          <Menu pizzas={pizzas} />
          <Burger burgers={burgers} />
          <Pasta pastas={pastas} />
          <Salad salads={salads} />
          <Drink drinks={drinks} />
        </main>
      </div>
    </Layout>
  );
}

export const getServerSideProps = async () => {
  const query = '*[_type == "pizza"]';
  const pizzas = await client.fetch(query);

  const query1 = '*[_type == "burger"]';
  const burgers = await client.fetch(query1);

  const query2 = '*[_type == "pasta"]';
  const pastas = await client.fetch(query2);

  const query3 = '*[_type == "salad"]';
  const salads = await client.fetch(query3);

  const query4 = `*[_type == "drink"]`;
  const drinks = await client.fetch(query4);
  return {
    props: { pizzas, burgers, pastas, salads, drinks },
  };
};
